framework:
    mailer:
        envelope:
            sender: 'no-replay@someone.com'
        headers:
            from: 'Рассылка нашего сайта <no-replay@someone.com>'
        dsn: '%env(MAILER_DSN)%'
